spring:
  config:
    activate:
      on-profile: prod

  jpa:
    hibernate:
      ddl-auto: validate  # DB테이블 구조 검증
    show-sql: false     # 성능 저하 방지
    properties:
      hibernate:
        default_batch_fetch_size: 100 # N+1 문제 방지 위해 배치 사이즈 설정
        dialect: org.hibernate.dialect.PostgreSQLDialect
    
logging:
  level:
    root: INFO
    com.back.coffeeprod: WARN  # 운영에서는 에러와 경고 위주 로그