-- 향미 노트와 추천 추출법을 변경 가능한 기준정보로 관리함
CREATE TABLE flavor_note
(
    flavor_note_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(50)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    description    TEXT,

    CONSTRAINT pk_flavor_note
        PRIMARY KEY (flavor_note_id),

    CONSTRAINT uk_flavor_note_code
        UNIQUE (code)
);

CREATE TABLE brew_method
(
    brew_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code           VARCHAR(50)  NOT NULL,
    name           VARCHAR(100) NOT NULL,
    description    TEXT,

    CONSTRAINT pk_brew_method
        PRIMARY KEY (brew_method_id),

    CONSTRAINT uk_brew_method_code
        UNIQUE (code)
);

-- 프로필별 향미 우선순위와 강도를 관리함
CREATE TABLE coffee_profile_flavor_note
(
    coffee_profile_flavor_note_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    coffee_profile_id             BIGINT   NOT NULL,
    flavor_note_id                BIGINT   NOT NULL,
    display_order                 SMALLINT NOT NULL,
    intensity                     SMALLINT NOT NULL,

    CONSTRAINT pk_coffee_profile_flavor_note
        PRIMARY KEY (coffee_profile_flavor_note_id),

    CONSTRAINT uk_coffee_profile_flavor_note_pair
        UNIQUE (coffee_profile_id, flavor_note_id),

    CONSTRAINT uk_coffee_profile_flavor_note_order
        UNIQUE (coffee_profile_id, display_order),

    CONSTRAINT fk_coffee_profile_flavor_note_profile
        FOREIGN KEY (coffee_profile_id)
            REFERENCES coffee_profile (coffee_profile_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_coffee_profile_flavor_note_note
        FOREIGN KEY (flavor_note_id)
            REFERENCES flavor_note (flavor_note_id)
            ON DELETE RESTRICT,

    CONSTRAINT ck_coffee_profile_flavor_note_order
        CHECK (display_order BETWEEN 1 AND 5),

    CONSTRAINT ck_coffee_profile_flavor_note_intensity
        CHECK (intensity BETWEEN 1 AND 5)
);

-- 프로필별 추천 추출법과 안내 문구를 관리함
CREATE TABLE coffee_profile_brew_method
(
    coffee_profile_brew_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    coffee_profile_id             BIGINT   NOT NULL,
    brew_method_id                BIGINT   NOT NULL,
    display_order                 SMALLINT NOT NULL,
    recommendation_note           VARCHAR(500),

    CONSTRAINT pk_coffee_profile_brew_method
        PRIMARY KEY (coffee_profile_brew_method_id),

    CONSTRAINT uk_coffee_profile_brew_method_pair
        UNIQUE (coffee_profile_id, brew_method_id),

    CONSTRAINT uk_coffee_profile_brew_method_order
        UNIQUE (coffee_profile_id, display_order),

    CONSTRAINT fk_coffee_profile_brew_method_profile
        FOREIGN KEY (coffee_profile_id)
            REFERENCES coffee_profile (coffee_profile_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_coffee_profile_brew_method_method
        FOREIGN KEY (brew_method_id)
            REFERENCES brew_method (brew_method_id)
            ON DELETE RESTRICT,

    CONSTRAINT ck_coffee_profile_brew_method_order
        CHECK (display_order BETWEEN 1 AND 3)
);