-- 커피 품종을 변경 가능한 기준정보로 관리함
CREATE TABLE coffee_variety
(
    coffee_variety_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code              VARCHAR(50)  NOT NULL,
    name              VARCHAR(100) NOT NULL,
    description       TEXT,

    CONSTRAINT pk_coffee_variety
        PRIMARY KEY (coffee_variety_id),

    CONSTRAINT uk_coffee_variety_code
        UNIQUE (code)
);

-- 프로필별 품종과 노출 순서를 관리함
CREATE TABLE coffee_profile_variety
(
    coffee_profile_variety_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    coffee_profile_id         BIGINT   NOT NULL,
    coffee_variety_id         BIGINT   NOT NULL,
    display_order             SMALLINT NOT NULL,

    CONSTRAINT pk_coffee_profile_variety
        PRIMARY KEY (coffee_profile_variety_id),

    CONSTRAINT uk_coffee_profile_variety_pair
        UNIQUE (coffee_profile_id, coffee_variety_id),

    CONSTRAINT uk_coffee_profile_variety_order
        UNIQUE (coffee_profile_id, display_order),

    CONSTRAINT fk_coffee_profile_variety_profile
        FOREIGN KEY (coffee_profile_id)
            REFERENCES coffee_profile (coffee_profile_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_coffee_profile_variety_variety
        FOREIGN KEY (coffee_variety_id)
            REFERENCES coffee_variety (coffee_variety_id)
            ON DELETE RESTRICT,

    CONSTRAINT ck_coffee_profile_variety_order
        CHECK (display_order BETWEEN 1 AND 3)
);

-- 품종 기준정보 삭제 검증과 역방향 조회 성능을 보장함
CREATE INDEX idx_coffee_profile_variety_coffee_variety_id
    ON coffee_profile_variety (coffee_variety_id);
