-- 블렌드 프로필의 원산지 구성과 비율을 관리함
CREATE TABLE coffee_profile_component
(
    coffee_profile_component_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    coffee_profile_id           BIGINT      NOT NULL,
    origin_country_code         VARCHAR(2)  NOT NULL,
    origin_region               VARCHAR(100),
    processing_method_id        BIGINT,
    component_ratio             NUMERIC(5, 2),
    display_order               SMALLINT    NOT NULL,

    CONSTRAINT pk_coffee_profile_component
        PRIMARY KEY (coffee_profile_component_id),

    CONSTRAINT uk_coffee_profile_component_order
        UNIQUE (coffee_profile_id, display_order),

    CONSTRAINT fk_coffee_profile_component_profile
        FOREIGN KEY (coffee_profile_id)
            REFERENCES coffee_profile (coffee_profile_id)
            ON DELETE RESTRICT,

    CONSTRAINT fk_coffee_profile_component_processing_method
        FOREIGN KEY (processing_method_id)
            REFERENCES processing_method (processing_method_id)
            ON DELETE RESTRICT,

    CONSTRAINT ck_coffee_profile_component_country_code
        CHECK (origin_country_code ~ '^[A-Z]{2}$'),

    CONSTRAINT ck_coffee_profile_component_ratio
        CHECK (
            component_ratio IS NULL
            OR component_ratio > 0 AND component_ratio <= 100
        ),

    CONSTRAINT ck_coffee_profile_component_order
        CHECK (display_order BETWEEN 1 AND 5)
);

-- 선택 FK의 조인 성능을 보조함
CREATE INDEX idx_coffee_profile_component_processing_method_id
    ON coffee_profile_component (processing_method_id)
    WHERE processing_method_id IS NOT NULL;
