-- 현재 JPA 엔티티 구조를 빈 PostgreSQL DB에 생성함
-- 후속 구조 변경은 별도 migration에서 처리함

CREATE TABLE member
(
    member_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    email      VARCHAR(100) NOT NULL,
    password   VARCHAR(255) NOT NULL,
    name       VARCHAR(50)  NOT NULL,
    nickname   VARCHAR(50)  NOT NULL,
    role       VARCHAR(255) NOT NULL,
    grade      VARCHAR(255) NOT NULL,
    mileage    INTEGER      NOT NULL DEFAULT 0,
    status     VARCHAR(255) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),

    CONSTRAINT pk_member
        PRIMARY KEY (member_id),

    CONSTRAINT uk_member_email
        UNIQUE (email),

    CONSTRAINT uk_member_nickname
        UNIQUE (nickname),

    CONSTRAINT ck_member_role
        CHECK (role IN ('USER', 'ADMIN')),

    CONSTRAINT ck_member_grade
        CHECK (grade IN ('BRONZE', 'SILVER', 'GOLD')),

    CONSTRAINT ck_member_status
        CHECK (status IN ('ACTIVE', 'SUSPENDED', 'WITHDRAWN'))
);

CREATE TABLE category
(
    category_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(50) NOT NULL,

    CONSTRAINT pk_category
        PRIMARY KEY (category_id)
);

CREATE TABLE product
(
    product_id     BIGINT GENERATED BY DEFAULT AS IDENTITY,
    category_id    BIGINT,
    name           VARCHAR(100) NOT NULL,
    price          INTEGER      NOT NULL,
    stock_quantity INTEGER      NOT NULL,
    roast_level    VARCHAR(255) NOT NULL,
    description    TEXT,
    image_url      VARCHAR(500),
    status         VARCHAR(255) NOT NULL,
    created_at     TIMESTAMP(6),
    updated_at     TIMESTAMP(6),

    CONSTRAINT pk_product
        PRIMARY KEY (product_id),

    CONSTRAINT fk_product_category
        FOREIGN KEY (category_id)
            REFERENCES category (category_id),

    CONSTRAINT ck_product_roast_level
        CHECK (roast_level IN ('LIGHT', 'MEDIUM', 'DARK')),

    CONSTRAINT ck_product_status
        CHECK (status IN ('ON_SALE', 'SOLD_OUT', 'HIDDEN'))
);

CREATE TABLE address
(
    address_id    BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id     BIGINT,
    recipient     VARCHAR(50)  NOT NULL,
    phone         VARCHAR(20)  NOT NULL,
    zipcode       VARCHAR(10)  NOT NULL,
    address_line1 VARCHAR(255) NOT NULL,
    address_line2 VARCHAR(255),
    is_default    BOOLEAN      NOT NULL,

    CONSTRAINT pk_address
        PRIMARY KEY (address_id),

    CONSTRAINT fk_address_member
        FOREIGN KEY (member_id)
            REFERENCES member (member_id)
);

CREATE TABLE cart
(
    cart_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id BIGINT,

    CONSTRAINT pk_cart
        PRIMARY KEY (cart_id),

    CONSTRAINT uk_cart_member
        UNIQUE (member_id),

    CONSTRAINT fk_cart_member
        FOREIGN KEY (member_id)
            REFERENCES member (member_id)
);

CREATE TABLE cart_item
(
    cart_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    cart_id      BIGINT,
    product_id   BIGINT,
    quantity     INTEGER      NOT NULL,
    grind_type   VARCHAR(255) NOT NULL,

    CONSTRAINT pk_cart_item
        PRIMARY KEY (cart_item_id),

    CONSTRAINT fk_cart_item_cart
        FOREIGN KEY (cart_id)
            REFERENCES cart (cart_id),

    CONSTRAINT fk_cart_item_product
        FOREIGN KEY (product_id)
            REFERENCES product (product_id),

    CONSTRAINT ck_cart_item_grind_type
        CHECK (
            grind_type IN (
                           'WHOLE_BEAN',
                           'ESPRESSO',
                           'DRIP',
                           'FRENCH_PRESS'
                )
            )
);

CREATE TABLE orders
(
    order_id            BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id           BIGINT,
    order_data          TIMESTAMP(6),
    status              VARCHAR(255) NOT NULL,
    used_mileage        INTEGER      NOT NULL,
    delivery_address    VARCHAR(255) NOT NULL,
    tracking_no         VARCHAR(255),
    toss_order_id       VARCHAR(64)  NOT NULL,
    product_total_price INTEGER      NOT NULL,
    delivery_fee        INTEGER      NOT NULL,
    earned_mileage      INTEGER      NOT NULL,
    total_price         INTEGER      NOT NULL,
    created_at          TIMESTAMP(6),
    updated_at          TIMESTAMP(6),

    CONSTRAINT pk_orders
        PRIMARY KEY (order_id),

    CONSTRAINT uk_orders_toss_order_id
        UNIQUE (toss_order_id),

    CONSTRAINT fk_orders_member
        FOREIGN KEY (member_id)
            REFERENCES member (member_id),

    CONSTRAINT ck_orders_status
        CHECK (
            status IN (
                       'PENDING',
                       'PAID',
                       'SHIPPED',
                       'DELIVERED',
                       'CANCELED'
                )
            )
);

CREATE TABLE order_item
(
    order_item_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id      BIGINT,
    product_id    BIGINT,
    order_price   INTEGER      NOT NULL,
    quantity      INTEGER      NOT NULL,
    grind_type    VARCHAR(255) NOT NULL,

    CONSTRAINT pk_order_item
        PRIMARY KEY (order_item_id),

    CONSTRAINT fk_order_item_order
        FOREIGN KEY (order_id)
            REFERENCES orders (order_id),

    CONSTRAINT fk_order_item_product
        FOREIGN KEY (product_id)
            REFERENCES product (product_id),

    CONSTRAINT ck_order_item_grind_type
        CHECK (
            grind_type IN (
                           'WHOLE_BEAN',
                           'ESPRESSO',
                           'DRIP',
                           'FRENCH_PRESS'
                )
            )
);

CREATE TABLE payment
(
    payment_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    order_id    BIGINT,
    pg_provider VARCHAR(50)  NOT NULL,
    payment_key VARCHAR(255) NOT NULL,
    pay_method  VARCHAR(20)  NOT NULL,
    status      VARCHAR(255) NOT NULL,
    paid_at     TIMESTAMP(6),

    CONSTRAINT pk_payment
        PRIMARY KEY (payment_id),

    CONSTRAINT fk_payment_order
        FOREIGN KEY (order_id)
            REFERENCES orders (order_id),

    CONSTRAINT ck_payment_status
        CHECK (status IN ('SUCCESS', 'FAILED', 'REFUNDED'))
);

CREATE TABLE reviews
(
    review_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id  BIGINT        NOT NULL,
    product_id BIGINT        NOT NULL,
    rating     INTEGER       NOT NULL,
    content    VARCHAR(1000) NOT NULL,
    created_at TIMESTAMP(6),
    updated_at TIMESTAMP(6),

    CONSTRAINT pk_reviews
        PRIMARY KEY (review_id),

    CONSTRAINT uk_review_member_product
        UNIQUE (member_id, product_id),

    CONSTRAINT fk_reviews_member
        FOREIGN KEY (member_id)
            REFERENCES member (member_id),

    CONSTRAINT fk_reviews_product
        FOREIGN KEY (product_id)
            REFERENCES product (product_id)
);

CREATE TABLE product_qna
(
    qna_id      BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id   BIGINT        NOT NULL,
    product_id  BIGINT        NOT NULL,
    answerer_id BIGINT,
    title       VARCHAR(200)  NOT NULL,
    question    VARCHAR(2000) NOT NULL,
    answer      VARCHAR(2000),
    status      VARCHAR(20)   NOT NULL,
    answered_at TIMESTAMP(6),
    created_at  TIMESTAMP(6),
    updated_at  TIMESTAMP(6),

    CONSTRAINT pk_product_qna
        PRIMARY KEY (qna_id),

    CONSTRAINT fk_product_qna_member
        FOREIGN KEY (member_id)
            REFERENCES member (member_id),

    CONSTRAINT fk_product_qna_product
        FOREIGN KEY (product_id)
            REFERENCES product (product_id),

    CONSTRAINT fk_product_qna_answerer
        FOREIGN KEY (answerer_id)
            REFERENCES member (member_id),

    CONSTRAINT ck_product_qna_status
        CHECK (status IN ('WAITING', 'ANSWERED'))
);

CREATE TABLE sales_statistics
(
    sales_statistics_id  BIGINT GENERATED BY DEFAULT AS IDENTITY,
    stat_date            DATE   NOT NULL,
    order_count          BIGINT NOT NULL,
    product_sales_amount BIGINT NOT NULL,
    delivery_fee_amount  BIGINT NOT NULL,
    used_mileage_amount  BIGINT NOT NULL,
    payment_amount       BIGINT NOT NULL,

    CONSTRAINT pk_sales_statistics
        PRIMARY KEY (sales_statistics_id),

    CONSTRAINT uk_sales_statistics_stat_date
        UNIQUE (stat_date)
);