-- 변경 가능한 가공 방식을 기준정보로 관리함
CREATE TABLE processing_method
(
    processing_method_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    code                 VARCHAR(50)  NOT NULL,
    name                 VARCHAR(100) NOT NULL,
    description          TEXT,

    CONSTRAINT pk_processing_method
        PRIMARY KEY (processing_method_id),

    CONSTRAINT uk_processing_method_code
        UNIQUE (code)
);

-- 추천 속성과 감각 정보를 판매 SKU에서 분리함
CREATE TABLE coffee_profile
(
    coffee_profile_id   BIGINT GENERATED BY DEFAULT AS IDENTITY,
    process_method_id   BIGINT,
    profile_name        VARCHAR(150) NOT NULL,
    bean_type           VARCHAR(30)  NOT NULL,
    origin_country_code CHAR(2),
    origin_region       VARCHAR(100),
    farm_or_cooperative VARCHAR(150),
    producer            VARCHAR(150),
    altitude_min        INTEGER,
    altitude_max        INTEGER,
    roast_level         VARCHAR(30)  NOT NULL,
    decaf               BOOLEAN      NOT NULL DEFAULT FALSE,
    decaf_method        VARCHAR(50),
    acidity             SMALLINT     NOT NULL,
    body                 SMALLINT     NOT NULL,
    sweetness            SMALLINT     NOT NULL,
    aroma                SMALLINT     NOT NULL,
    summary              TEXT,
    created_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at           TIMESTAMPTZ  NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_coffee_profile
        PRIMARY KEY (coffee_profile_id),

    CONSTRAINT fk_coffee_profile_processing_method
        FOREIGN KEY (process_method_id)
            REFERENCES processing_method (processing_method_id),

    CONSTRAINT ck_coffee_profile_bean_type
        CHECK (bean_type IN ('SINGLE_ORIGIN', 'BLEND')),

    CONSTRAINT ck_coffee_profile_roast_level
        CHECK (roast_level IN ('LIGHT', 'MEDIUM', 'DARK')),

    CONSTRAINT ck_coffee_profile_origin
        CHECK (
            (bean_type = 'SINGLE_ORIGIN'
                AND origin_country_code IS NOT NULL)
                OR
            (bean_type = 'BLEND'
                AND origin_country_code IS NULL)
            ),

    CONSTRAINT ck_coffee_profile_country_code
        CHECK (
            origin_country_code IS NULL
                OR origin_country_code ~ '^[A-Z]{2}$'
),

    CONSTRAINT ck_coffee_profile_altitude_min
        CHECK (altitude_min IS NULL OR altitude_min >= 0),

    CONSTRAINT ck_coffee_profile_altitude_max
        CHECK (
            altitude_max IS NULL
            OR (
                altitude_min IS NOT NULL
                AND altitude_max >= altitude_min
            )
        ),

    CONSTRAINT ck_coffee_profile_decaf
        CHECK (decaf OR decaf_method IS NULL),

    CONSTRAINT ck_coffee_profile_acidity
        CHECK (acidity BETWEEN 1 AND 5),

    CONSTRAINT ck_coffee_profile_body
        CHECK (body BETWEEN 1 AND 5),

    CONSTRAINT ck_coffee_profile_sweetness
        CHECK (sweetness BETWEEN 1 AND 5),

    CONSTRAINT ck_coffee_profile_aroma
        CHECK (aroma BETWEEN 1 AND 5)
);