-- 회원별 커피 취향을 하나만 저장함
CREATE TABLE member_coffee_preference
(
    member_coffee_preference_id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    member_id                   BIGINT      NOT NULL,
    processing_method_id        BIGINT,
    bean_type                   VARCHAR(30),
    roast_level                 VARCHAR(30),
    decaf                       BOOLEAN,
    preferred_acidity           SMALLINT,
    preferred_body              SMALLINT,
    preferred_sweetness         SMALLINT,
    preferred_aroma             SMALLINT,
    created_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at                  TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_member_coffee_preference
        PRIMARY KEY (member_coffee_preference_id),

    CONSTRAINT uk_member_coffee_preference_member
        UNIQUE (member_id),

    CONSTRAINT fk_member_coffee_preference_member
        FOREIGN KEY (member_id)
            REFERENCES member (member_id),

    CONSTRAINT fk_member_coffee_preference_processing_method
        FOREIGN KEY (processing_method_id)
            REFERENCES processing_method (processing_method_id),

    CONSTRAINT ck_member_coffee_preference_bean_type
        CHECK (
            bean_type IS NULL
                OR bean_type IN ('SINGLE_ORIGIN', 'BLEND')
            ),

    CONSTRAINT ck_member_coffee_preference_roast_level
        CHECK (
            roast_level IS NULL
                OR roast_level IN ('LIGHT', 'MEDIUM', 'DARK')
            ),

    CONSTRAINT ck_member_coffee_preference_acidity
        CHECK (
            preferred_acidity IS NULL
                OR preferred_acidity BETWEEN 1 AND 5
            ),

    CONSTRAINT ck_member_coffee_preference_body
        CHECK (
            preferred_body IS NULL
                OR preferred_body BETWEEN 1 AND 5
            ),

    CONSTRAINT ck_member_coffee_preference_sweetness
        CHECK (
            preferred_sweetness IS NULL
                OR preferred_sweetness BETWEEN 1 AND 5
            ),

    CONSTRAINT ck_member_coffee_preference_aroma
        CHECK (
            preferred_aroma IS NULL
                OR preferred_aroma BETWEEN 1 AND 5
            ),

    CONSTRAINT ck_member_coffee_preference_required
        CHECK (
            processing_method_id IS NOT NULL
                OR bean_type IS NOT NULL
                OR roast_level IS NOT NULL
                OR decaf IS NOT NULL
                OR preferred_acidity IS NOT NULL
                OR preferred_body IS NOT NULL
                OR preferred_sweetness IS NOT NULL
                OR preferred_aroma IS NOT NULL
            )
);